/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateSnapshot = /* GraphQL */ `
  subscription OnCreateSnapshot($filter: ModelSubscriptionSnapshotFilterInput) {
    onCreateSnapshot(filter: $filter) {
      id
      timestamp
      planYear
      planTitle
      projectTitle
      projectDescription
      projectRank
      projectFunding
      projectHeadcount
      initiativeTitle
      initiativeDescription
      organizationName
      organizationManagerAlias
      ownerAlias
      goalTitle
      goalDescription
      snapshotPlanId
      snapshotProjectId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateSnapshot = /* GraphQL */ `
  subscription OnUpdateSnapshot($filter: ModelSubscriptionSnapshotFilterInput) {
    onUpdateSnapshot(filter: $filter) {
      id
      timestamp
      planYear
      planTitle
      projectTitle
      projectDescription
      projectRank
      projectFunding
      projectHeadcount
      initiativeTitle
      initiativeDescription
      organizationName
      organizationManagerAlias
      ownerAlias
      goalTitle
      goalDescription
      snapshotPlanId
      snapshotProjectId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteSnapshot = /* GraphQL */ `
  subscription OnDeleteSnapshot($filter: ModelSubscriptionSnapshotFilterInput) {
    onDeleteSnapshot(filter: $filter) {
      id
      timestamp
      planYear
      planTitle
      projectTitle
      projectDescription
      projectRank
      projectFunding
      projectHeadcount
      initiativeTitle
      initiativeDescription
      organizationName
      organizationManagerAlias
      ownerAlias
      goalTitle
      goalDescription
      snapshotPlanId
      snapshotProjectId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateGoal = /* GraphQL */ `
  subscription OnCreateGoal($filter: ModelSubscriptionGoalFilterInput) {
    onCreateGoal(filter: $filter) {
      id
      title
      description
      status
      type
      class
      start
      end
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      goalPlanId
      goalOrganizationId
      goalOwnerId
      goalParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateGoal = /* GraphQL */ `
  subscription OnUpdateGoal($filter: ModelSubscriptionGoalFilterInput) {
    onUpdateGoal(filter: $filter) {
      id
      title
      description
      status
      type
      class
      start
      end
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      goalPlanId
      goalOrganizationId
      goalOwnerId
      goalParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteGoal = /* GraphQL */ `
  subscription OnDeleteGoal($filter: ModelSubscriptionGoalFilterInput) {
    onDeleteGoal(filter: $filter) {
      id
      title
      description
      status
      type
      class
      start
      end
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      goalPlanId
      goalOrganizationId
      goalOwnerId
      goalParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateProject = /* GraphQL */ `
  subscription OnCreateProject($filter: ModelSubscriptionProjectFilterInput) {
    onCreateProject(filter: $filter) {
      id
      title
      description
      rank
      funding
      headcount
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Initiative {
        id
        title
        description
        rank
        bucket
        status
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Theme {
          id
          title
          description
          themePlanId
          createdAt
          updatedAt
          __typename
        }
        Sponsor {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        initiativePlanId
        initiativeThemeId
        initiativeSponsorId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Goal {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      projectPlanId
      projectInitiativeId
      projectOrganizationId
      projectOwnerId
      projectGoalId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateProject = /* GraphQL */ `
  subscription OnUpdateProject($filter: ModelSubscriptionProjectFilterInput) {
    onUpdateProject(filter: $filter) {
      id
      title
      description
      rank
      funding
      headcount
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Initiative {
        id
        title
        description
        rank
        bucket
        status
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Theme {
          id
          title
          description
          themePlanId
          createdAt
          updatedAt
          __typename
        }
        Sponsor {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        initiativePlanId
        initiativeThemeId
        initiativeSponsorId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Goal {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      projectPlanId
      projectInitiativeId
      projectOrganizationId
      projectOwnerId
      projectGoalId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteProject = /* GraphQL */ `
  subscription OnDeleteProject($filter: ModelSubscriptionProjectFilterInput) {
    onDeleteProject(filter: $filter) {
      id
      title
      description
      rank
      funding
      headcount
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Initiative {
        id
        title
        description
        rank
        bucket
        status
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Theme {
          id
          title
          description
          themePlanId
          createdAt
          updatedAt
          __typename
        }
        Sponsor {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        initiativePlanId
        initiativeThemeId
        initiativeSponsorId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      Owner {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Goal {
        id
        title
        description
        status
        type
        class
        start
        end
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        Owner {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          title
          description
          status
          type
          class
          start
          end
          goalPlanId
          goalOrganizationId
          goalOwnerId
          goalParentId
          createdAt
          updatedAt
          __typename
        }
        goalPlanId
        goalOrganizationId
        goalOwnerId
        goalParentId
        createdAt
        updatedAt
        __typename
      }
      projectPlanId
      projectInitiativeId
      projectOrganizationId
      projectOwnerId
      projectGoalId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreatePerson = /* GraphQL */ `
  subscription OnCreatePerson($filter: ModelSubscriptionPersonFilterInput) {
    onCreatePerson(filter: $filter) {
      id
      alias
      name
      email
      status
      sixManagerAlias
      isManager
      isBizOps
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      personPlanId
      personManagerId
      personOrganizationId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdatePerson = /* GraphQL */ `
  subscription OnUpdatePerson($filter: ModelSubscriptionPersonFilterInput) {
    onUpdatePerson(filter: $filter) {
      id
      alias
      name
      email
      status
      sixManagerAlias
      isManager
      isBizOps
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      personPlanId
      personManagerId
      personOrganizationId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeletePerson = /* GraphQL */ `
  subscription OnDeletePerson($filter: ModelSubscriptionPersonFilterInput) {
    onDeletePerson(filter: $filter) {
      id
      alias
      name
      email
      status
      sixManagerAlias
      isManager
      isBizOps
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Organization {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      personPlanId
      personManagerId
      personOrganizationId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateOrganization = /* GraphQL */ `
  subscription OnCreateOrganization(
    $filter: ModelSubscriptionOrganizationFilterInput
  ) {
    onCreateOrganization(filter: $filter) {
      id
      name
      description
      headcount
      incTarget
      mgrTarget
      icTarget
      peTarget
      pmTarget
      tpmTarget
      argTarget
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      organizationPlanId
      organizationManagerId
      organizationParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateOrganization = /* GraphQL */ `
  subscription OnUpdateOrganization(
    $filter: ModelSubscriptionOrganizationFilterInput
  ) {
    onUpdateOrganization(filter: $filter) {
      id
      name
      description
      headcount
      incTarget
      mgrTarget
      icTarget
      peTarget
      pmTarget
      tpmTarget
      argTarget
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      organizationPlanId
      organizationManagerId
      organizationParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteOrganization = /* GraphQL */ `
  subscription OnDeleteOrganization(
    $filter: ModelSubscriptionOrganizationFilterInput
  ) {
    onDeleteOrganization(filter: $filter) {
      id
      name
      description
      headcount
      incTarget
      mgrTarget
      icTarget
      peTarget
      pmTarget
      tpmTarget
      argTarget
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Manager {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      Parent {
        id
        name
        description
        headcount
        incTarget
        mgrTarget
        icTarget
        peTarget
        pmTarget
        tpmTarget
        argTarget
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Parent {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        organizationPlanId
        organizationManagerId
        organizationParentId
        createdAt
        updatedAt
        __typename
      }
      organizationPlanId
      organizationManagerId
      organizationParentId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateInitiative = /* GraphQL */ `
  subscription OnCreateInitiative(
    $filter: ModelSubscriptionInitiativeFilterInput
  ) {
    onCreateInitiative(filter: $filter) {
      id
      title
      description
      rank
      bucket
      status
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Theme {
        id
        title
        description
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        themePlanId
        createdAt
        updatedAt
        __typename
      }
      Sponsor {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      initiativePlanId
      initiativeThemeId
      initiativeSponsorId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateInitiative = /* GraphQL */ `
  subscription OnUpdateInitiative(
    $filter: ModelSubscriptionInitiativeFilterInput
  ) {
    onUpdateInitiative(filter: $filter) {
      id
      title
      description
      rank
      bucket
      status
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Theme {
        id
        title
        description
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        themePlanId
        createdAt
        updatedAt
        __typename
      }
      Sponsor {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      initiativePlanId
      initiativeThemeId
      initiativeSponsorId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteInitiative = /* GraphQL */ `
  subscription OnDeleteInitiative(
    $filter: ModelSubscriptionInitiativeFilterInput
  ) {
    onDeleteInitiative(filter: $filter) {
      id
      title
      description
      rank
      bucket
      status
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      Theme {
        id
        title
        description
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        themePlanId
        createdAt
        updatedAt
        __typename
      }
      Sponsor {
        id
        alias
        name
        email
        status
        sixManagerAlias
        isManager
        isBizOps
        Plan {
          id
          title
          description
          year
          ktloTarget
          status
          createdAt
          updatedAt
          __typename
        }
        Manager {
          id
          alias
          name
          email
          status
          sixManagerAlias
          isManager
          isBizOps
          personPlanId
          personManagerId
          personOrganizationId
          createdAt
          updatedAt
          __typename
        }
        Organization {
          id
          name
          description
          headcount
          incTarget
          mgrTarget
          icTarget
          peTarget
          pmTarget
          tpmTarget
          argTarget
          organizationPlanId
          organizationManagerId
          organizationParentId
          createdAt
          updatedAt
          __typename
        }
        personPlanId
        personManagerId
        personOrganizationId
        createdAt
        updatedAt
        __typename
      }
      initiativePlanId
      initiativeThemeId
      initiativeSponsorId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateTheme = /* GraphQL */ `
  subscription OnCreateTheme($filter: ModelSubscriptionThemeFilterInput) {
    onCreateTheme(filter: $filter) {
      id
      title
      description
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      themePlanId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateTheme = /* GraphQL */ `
  subscription OnUpdateTheme($filter: ModelSubscriptionThemeFilterInput) {
    onUpdateTheme(filter: $filter) {
      id
      title
      description
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      themePlanId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteTheme = /* GraphQL */ `
  subscription OnDeleteTheme($filter: ModelSubscriptionThemeFilterInput) {
    onDeleteTheme(filter: $filter) {
      id
      title
      description
      Plan {
        id
        title
        description
        year
        ktloTarget
        status
        createdAt
        updatedAt
        __typename
      }
      themePlanId
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreatePlan = /* GraphQL */ `
  subscription OnCreatePlan($filter: ModelSubscriptionPlanFilterInput) {
    onCreatePlan(filter: $filter) {
      id
      title
      description
      year
      ktloTarget
      status
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdatePlan = /* GraphQL */ `
  subscription OnUpdatePlan($filter: ModelSubscriptionPlanFilterInput) {
    onUpdatePlan(filter: $filter) {
      id
      title
      description
      year
      ktloTarget
      status
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeletePlan = /* GraphQL */ `
  subscription OnDeletePlan($filter: ModelSubscriptionPlanFilterInput) {
    onDeletePlan(filter: $filter) {
      id
      title
      description
      year
      ktloTarget
      status
      createdAt
      updatedAt
      __typename
    }
  }
`;
